export const rows = [
  {
    id: 1,
    name: "Ali Mohamed",
    email: "ali_mohamed@example.com",
    age: 20,
    phone: "0123456789",
    access: "User",
  },
  {
    id: 2,
    name: "Aya Mohamed",
    email: "aya_mohamed@example.com",
    age: 40,
    phone: "9876543210",
    access: "Admin",
  },
  {
    id: 3,
    name: "Omar Khaled",
    email: "omar_khaled@example.com",
    age: 20,
    phone: "1234567890",
    access: "Admin",
  },
  {
    id: 4,
    name: "Yara Abdelrahman",
    email: "yara_abdelrahman@example.com",
    age: 35,
    phone: "5678901234",
    access: "Admin",
  },
  {
    id: 5,
    name: "Adam Youssef",
    email: "adam_youssef@example.com",
    age: 25,
    phone: "6789012345",
    access: "User",
  },
  {
    id: 6,
    name: "Sara Ibrahim",
    email: "sara_ibrahim@example.com",
    age: 30,
    phone: "7890123456",
    access: "User",
  },
  {
    id: 7,
    name: "Ali Mahmoud",
    email: "ali_mahmoud@example.com",
    age: 33,
    phone: "8901234567",
    access: "Manager",
  },
  {
    id: 8,
    name: "Lina Hamdy",
    email: "lina_hamdy@example.com",
    age: 22,
    phone: "9012345678",
    access: "Manager",
  },
  {
    id: 9,
    name: "Youssef Omar",
    email: "youssef_omar@example.com",
    age: 24,
    phone: "0987654321",
    access: "Manager",
  },
];
